version: "3.7"

services:
    app:
        # Build하려는 Dockerfile의 위치
        build: .

        image: homelab-health-checker-image
        ports:
            - 3456:3456
        tty: true
        volumes:
            # バインドマウント
            - ./app:/app
